[package]
name = "check-ip"
version = "1.0.0"
edition = "2021"

[dependencies]
clap = { version = "^3", features = ["derive", "cargo", "env", "regex", "wrap_help", "unicode"] }
log = { version = "^0.4", features = [ "std" ] }
regex = "^1"
lazy_static = "^1"
signal-hook = "^0.3"
