[package]
name = "check-battery"
version = "1.0.0"
edition = "2021"

[dependencies]
script-lib = { path = "../../", features = [ "battery", "logging", "notif" ] }
clap = { version = "^4", features = ["derive", "cargo", "env", "wrap_help", "unicode"] }
log = { version = "^0.4", features = [ "std" ] }
notify-rust = { version = "^4", default-features = false, features = ["d", "images"] }
regex = "^1"
lazy_static = "^1"
directories = "^4"
serde = { version = "^1", features = ["derive"] }
bincode = "^1"
