[package]
name = "shell-prompt"
version = "1.0.0"
edition = "2021"

[dependencies]
script-lib = { path = "../../", features = [ "battery", "logging" ] }
clap = { version = "^4", features = ["derive", "cargo", "env", "wrap_help", "unicode"] }
log = { version = "^0.4", features = [ "std" ] }
time = { version = "^0.3", features = ["formatting", "local-offset", "macros"] }
git2 = "^0.15"
console = "^0.15"
